pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'tacz'

def simpleBedrockModelBuild = [
        file('../simplebedrockmodel'),
        file('../FPSMatch/porting/simplebedrockmodel')
].find { it.exists() }
if (simpleBedrockModelBuild != null) {
    includeBuild(simpleBedrockModelBuild) {
        dependencySubstitution {
            substitute module('com.github.mcmodderanchor:simplebedrockmodel') using project(':')
        }
    }
}
